source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Mirror_Example', :exclusive => true do
  pod "Mirror", :path => "../"
end

target 'Mirror_Tests', :exclusive => true do
  pod "Mirror", :path => "../"

  pod 'Quick', '~> 0.4.0'
  pod 'Nimble', :git => 'https://github.com/Quick/Nimble.git', :branch => "swift-2.0"
end
